services:
  streamlit:
    build:
      context: ./Streamlit APP
      dockerfile: Dockerfile
    ports:
      - "8501:8501" 
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./FastAPI APP
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge